### ISSUE TITLE
日志文件名日期错误

### ISSUE THREAD

**Issue by IndigoRCS** [MrXiaoM/Overflow#10]
### 问题描述

在`2023-12-31`这一天，`logs`下产生了一个名为`2024-12-31.log`的日志文件

![image](https://github.com/MrXiaoM/Overflow/assets/46233705/d984b25d-cbcb-430b-8229-11fc42d58266)

### 复现

emmmm把电脑日期调到`2023-12-31`？

### Overflow 版本

1bf69de

**Comment by MrXiaoM** [comment]
这个问题原生 mirai 也有，我没装 Overflow 的 mirai 也出现了…

**Comment by IndigoRCS** [comment]
Amazing...
那既然是mirai自身的问题，这个issue就close了

**Comment by MrXiaoM** [comment]
https://github.com/mamoe/mirai/blob/dev/mirai-console/frontend/mirai-console-frontend-base/src/logging/LogRecorder.kt#L110
