### ISSUE TITLE
机器人接受文件之后，显示overflow 未知事件，我看是支持文件接受的把

### ISSUE THREAD

**Issue by kzsuprecr** [MrXiaoM/Overflow#112]
### 问题描述

overflow最新发行版本，加LLOnebot最新版本4.4.2，qq版本9.9.16-28971, 机器人群文件接受到信息之后，overflow直接显示为位置事件，希望解答一下，刚接触这一块，thanks
![image](https://github.com/user-attachments/assets/1126c0b5-9d29-4b2d-8606-4e5369473407)
![a6abc7af86dd7989c2df866a329bc58c](https://github.com/user-attachments/assets/dde33bc6-1e43-4aa8-b93c-9b413d10f99a)

### 复现

机器人收到群文件

### Overflow 版本

1.0.0

### 其他组件版本

overflow最新发行版本，加LLOnebot最新版本4.4.2，qq版本9.9.16-28971

### 系统日志

```text
W/Overflow: 接收到来自协议端的未知事件 {"time":1733297888,"self_id":1690099502,"post_type":"notice","notice_type":"group_upload","file":{"id":"/36c8fdf2-8da7-4c15-9bf8-d694f26988eb","name":"123.txt","size":17,"busid":102},"group_id":263955793,"user_id":3023469406}
```

### 网络日志

```text
1
```

### 补充信息

1

**Comment by MrXiaoM** [comment]
mirai 没有文件上传事件，日志里已经能看到警告下面有一条 接收到 WrappedFileMessage 了，插件是能依此接收到文件上传通知的，这个警告可以忽略。

**Comment by kzsuprecr** [comment]
确实是能接受文件上传通知的，可是没法获得文件的任何信息。是需要我们自己去group里面拿上传文件然后自己根据上传事件处理吗，有点懵

**Comment by MrXiaoM** [comment]
我按我接收到的文件消息做了调整，应该能收到正确的参数了

**Comment by kzsuprecr** [comment]
> 我按我接收到的文件消息做了调整，应该能收到正确的参数了

确实可以接受文件了，但我有个问题，我是开发插件用你的模板overflow-console-plugin-template-master，我把这个项目用gradle的jar方法打包之后三个文件导入模板方法中，就无法启动，有点不太懂，是缺少了
![3da36715ce6729cb2dba2a05fbed3012](https://github.com/user-attachments/assets/096ab043-b7dd-4f91-99f2-eeb2f3f3ddc4)
jar包吗

**Comment by kzsuprecr** [comment]
> 我按我接收到的文件消息做了调整，应该能收到正确的参数了

我是用这个项目的gradle的clean 然后jar 或者build 形成的3个jar包，然后把模板项目的那几个去掉依赖，然后手动导入本地的jar包，感觉是不是我哪步操作有问题 求教，困惑了

**Comment by kzsuprecr** [comment]
> > 我按我接收到的文件消息做了调整，应该能收到正确的参数了
> 
> 我是用这个项目的gradle的clean 然后jar 或者build 形成的3个jar包，然后把模板项目的那几个去掉依赖，然后手动导入本地的jar包，感觉是不是我哪步操作有问题 求教，困惑了

用的是RunMirai.kt 这个类启动

**Comment by MrXiaoM** [comment]
使用 overflow-core-all 模块打包出来的 -all.jar 就行了

**Comment by MrXiaoM** [comment]
另外，开发版本有发布到 sonatype s01 仓库，如果你没对 overflow 做修改，不需要自己编译

**Comment by kzsuprecr** [comment]
> 使用 overflow-core-all 模块打包出来的 -all.jar 就行了
我也用这个打了，这玩意打出来只有1kb，
![0e7f2e8da4bc714863bf908d0de293f2](https://github.com/user-attachments/assets/fd113c94-797f-4614-9ec9-736cae80929a)
![Uploading d2b72cf82adf171954872ac021b0a47c.png…]()

**Comment by MrXiaoM** [comment]
运行 shadowJar 啊

**Comment by kzsuprecr** [comment]
> 运行 shadowJar 啊

感谢感谢，搞定了，第一次搞gradle和kotlin
