### ISSUE TITLE
在OneBot实现端使用QC码时机器人不回复

### ISSUE THREAD

**Issue by zzj2039** [MrXiaoM/Overflow#14]
### 问题描述

使用openShamrock对接并启用QC码格式，机器人不处理全局指令
带/时回复正常
`2024-01-24 08:32:25 V/Bot.2584574762: [季落秋风 - Minecraft(806915610)] 服主-梓不过是枫(2039475150) -> "/wifeyouwant"
2024-01-24 08:32:25 V/Bot.2584574762: Group(806915610) <- 变态渣男插件 - 帮助
  /wuw reload - 重载配置文件`
不带/的全局指令不处理
`2024-01-24 08:32:34 V/Bot.2584574762: [季落秋风 - Minecraft(806915610)] 服主-梓不过是枫(2039475150) -> "抽老婆"`

### 复现

使用openShamrock对接并启用QC码

### Overflow 版本

2.16.0-19e495b

**Comment by MrXiaoM** [comment]
Overflow 不支持cq码格式消息，关闭cq码
