### ISSUE TITLE
被动 WebSocket 时服务端不响应用户发出的指令信息

### ISSUE THREAD

**Issue by Lssg97** [MrXiaoM/Overflow#23]
### 问题描述

被动 WebSocket 时 bot 貌似无法接收来自聊天中的指令。试过两个基于 MiraiConsole 的插件都不行，对来自 QQ 信息发出的指令完全无响应，而基于 MCL 的 mirai 是可用的。所以推测可能是 Overflow 的问题，不知到主动 WebSocket 是否也有此问题。

### 复现

最开始的测试插件为 [JNR](https://mirai.mamoe.net/topic/745/) 和 [BilibiliDynamic MiraiPlugin](https://mirai.mamoe.net/topic/792)。

客户端服务端通讯一切正常，服务端可以使用 `/overflow friend` 命令发送消息，也能接收到客户端发来的私聊指令消息，但是不会对指令做出任何反应。

最后尝试了一下直接用 `/permission add  <QQ 号> *` 命令赋予用户全部指令权限，用户打出 `/help` 仍无反应。

![无标题](https://github.com/MrXiaoM/Overflow/assets/47817993/46b18600-9596-4295-92f1-83025cf9db92)

### Overflow 版本

795845b

### 其他组件版本

在 Windows Server 2019 (17763.1339) 使用 [mumu 模拟器 v3.7.10](https://a11.gdl.netease.com/MuMuInstaller_3.1.6.0_V3.7.10.2634_zh-Hans_1706267805.exe)，[QQ v8.9.80.12440](https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_8.9.80_64.apk)，[Kitsune Magisk R65C33E4F](https://github.com/HuskyDG/magisk-files/releases/tag/1707294287)，[LSPosed-v1.9.2-7024-zygisk-release](https://github.com/LSPosed/LSPosed/releases/tag/v1.9.2)，[Shamrock-v1.0.8.r317.63ce2d4-all](https://github.com/whitechi73/OpenShamrock/actions/runs/7925364323) 搭建客户端；在 Ubuntu 20.04.6 LTS 使用 overflow-2.16.0-795845b-SNAPSHOT 整合包搭建服务端。

### 系统日志

```text
没有任何相关报错，推测 overflow 没有正确将消息传递给 mirai？
```

**Comment by MrXiaoM** [comment]
安装 chat-command 了吗

**Comment by Lssg97** [comment]
> 安装 chat-command 了吗

确实是它的原因……是我自己的问题😂。我给服务端构建了 docker，插件没传递进去。
