### ISSUE TITLE
[建议]对Lagrange合并转发提供支持

### ISSUE THREAD

**Issue by ikunsz666** [MrXiaoM/Overflow#30]
已使用最新版Overflow，连接Lagrange，无法发送合并转发消息（node）。
自己研究了下发现了问题，拉格兰发送转发消息的时候，“uin”的值为qq号的字符串型，如果正常传入整数型会导致拉格兰报错并且无法发送。
是否考虑增加一个配置项以适配合并转发？

**Comment by ikunsz666** [comment]
> 已使用最新版Overflow，连接Lagrange，无法发送合并转发消息（node）。 自己研究了下发现了问题，拉格兰发送转发消息的时候，“uin”的值为qq号的字符串型，如果正常传入整数型会导致拉格兰报错并且无法发送。 是否考虑增加一个配置项以适配合并转发？

看到还在open的一个issue已经有反映合并转发这个问题了
[合并转发消息节点](https://docs.go-cqhttp.org/cqcode/#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF%E8%8A%82%E7%82%B9)
文档里注明的uin类型为int64类型，不过下翻找到“自定义消息合并转发”时可以发现uin为字符串型，文档与示例不一致。

**Comment by ikunsz666** [comment]
![image](https://github.com/MrXiaoM/Overflow/assets/124548189/3321aeb5-7b6e-4ab0-bebc-f07518bd30c6)
![image](https://github.com/MrXiaoM/Overflow/assets/124548189/8d69f7db-3ca0-4e61-b2a5-bae0a1f51e8b)

**Comment by MrXiaoM** [comment]
```kotlin
import cn.evolvefield.onebot.client.core.toJsonArray
import com.google.gson.GsonBuilder
import com.google.gson.JsonParser
import net.mamoe.mirai.message.data.At
import net.mamoe.mirai.message.data.ForwardMessage
import net.mamoe.mirai.message.data.PlainText
import net.mamoe.mirai.utils.currentTimeSeconds
import top.mrxiaom.overflow.internal.message.OnebotMessages

object LagrangeTest {
    @JvmStatic
    fun main(args: Array<String>) {
        val gson = GsonBuilder().setPrettyPrinting().create()
        val nodeList = listOf(
            ForwardMessage.Node(12345, currentTimeSeconds().toInt(), "测试", PlainText("消息1")),
            ForwardMessage.Node(123456, currentTimeSeconds().toInt(), "测试", At(12345).plus("消息2")),
            ForwardMessage.Node(1234567, currentTimeSeconds().toInt(), "测试", At(123456).plus("消息3")),
            ForwardMessage.Node(12345678, currentTimeSeconds().toInt(), "测试", At(1234567).plus("消息4")),
        ).map {
            val message = JsonParser.parseString(OnebotMessages.serializeToOneBotJson(null, it.messageChain))
            mutableMapOf(
                "type" to "node",
                "data" to mutableMapOf(
                    "name" to it.senderName,
                    "uin" to it.senderId,
                    "content" to message,
                ),
                "time" to it.time
            )
        }
        println(gson.toJson(nodeList.toJsonArray()))
    }
}
```
![QQ截图20240316145243](https://github.com/MrXiaoM/Overflow/assets/35788433/098db5b2-edf2-4203-aa7a-356a43c140ae)

写了个测试，并没有发现 uin 为字符串类型的情况。

序列化转发消息的部分：[OnebotMessages.kt#serializeForwardNodes](https://github.com/MrXiaoM/Overflow/blob/main/overflow-core/src/main/kotlin/top/mrxiaom/overflow/internal/message/OnebotMessages.kt#L218-L226)

**Comment by MrXiaoM** [comment]
了解了，Lagrange 似乎用的是 [Onebot](https://github.com/KonataDev/Lagrange.Core/blob/master/Lagrange.OneBot/Core/Entity/Message/OneBotNode.cs) 而非 go-cqhttp 的转发格式，之前弄混了

**Comment by ikunsz666** [comment]
qs

**Comment by ikunsz666** [comment]
![ff31deb8310a3ee8440401192a7d3f33](https://github.com/MrXiaoM/Overflow/assets/124548189/c2c21f69-4e67-49a7-8b90-d869e5ea2a35)
拉格兰特色

**Comment by MrXiaoM** [comment]
已尝试在 2cf7991 修复

**Comment by ikunsz666** [comment]
好的，稍晚些测试

**Comment by ikunsz666** [comment]
无法发送转发消息，会提示“消息类型不支持查看”

**Comment by MrXiaoM** [comment]
> 无法发送转发消息，会提示“消息类型不支持查看”

这是 Lagrange 实现的问题

**Comment by MrXiaoM** [comment]
#31
