### ISSUE TITLE
是否可以支持satori协议

### ISSUE THREAD

**Issue by killerprojecte** [MrXiaoM/Overflow#33]
支持Satori协议 这样可以不需要部署Lagrange或者OpenShamrock直接使用chronocat进行部署

这样的好处就是不需要用到签名 同时也不需要虚拟机 也可以在无头环境下运行

**Comment by MrXiaoM** [comment]
不会支持除了 Onebot 以外的任何协议，包括 Kritor

**Comment by MrXiaoM** [comment]
越来越多新协议会让 Overflow 变得臃肿，要支持只能写独立运行的转接器。

**Comment by killerprojecte** [comment]
@MrXiaoM 
可以考虑提供adapter的接口吗 将现有onebot协议移动至overflow-adapter-onebot这样 供其他开发者实现其他协议
