### ISSUE TITLE
使用拉格朗日有些群消息无法获取

### ISSUE THREAD

**Issue by QAQ2333333** [MrXiaoM/Overflow#35]
### 问题描述

在有些群聊里的消息可以被拉格朗日接收到，但是在overflow里无法接收。（因为是部署在树莓派上，没有远程桌面，所以只能拍照，请见谅）不知道是为什么
![1b172909d00fe5e211450a1981b7bc14](https://github.com/MrXiaoM/Overflow/assets/102404379/170d7ffd-7fa6-4d7a-83b8-fea021a74c8a)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=6517431017753148198 skey=@crypt_91ea7dcc_835686ad7ee54b41fd7deab16a508e99 mmweb_appid=wx_webfilehelper](https://github.com/MrXiaoM/Overflow/assets/102404379/f7bf9096-1d36-4623-ad6d-fcb120fd2563)

### 复现

在某些群的消息

### Overflow 版本

213cf4d

### 其他组件版本

[44477b9](https://github.com/KonataDev/Lagrange.Core/commit/44477b9ee9ee1c7de6d34b223fc6035ce0314704)

**Comment by MrXiaoM** [comment]
字面意思，无法从 Lagrange 取得相关群的信息
