### ISSUE TITLE
无法启动，显示错误：无法初始化主类 net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader

### ISSUE THREAD

**Issue by Kesunorin** [MrXiaoM/Overflow#4]
**问题描述**
start.sh脚本启动后显示
```
错误: 无法初始化主类 net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader
原因: java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope
```
按照用户手册方法三安装，依次准备了三个文件 `mirai-console-2.16.0-all.jar` `mirai-console-terminal-2.16.0-all.jar` `overflow-core-all-2.16.0-all.jar`
创建 `libs` 文件夹，将以上内容放入该文件夹。
使用 `start.sh`(Linux/MacOS) 如下
```shell
java -cp "$CLASSPATH:./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader
```
**overflow版本**
overflow版本：`overflow-core-all-5194d53`

**Comment by Kesunorin** [comment]
overflow版本退回overflow-core-all-ccaadf8解决

**Comment by MrXiaoM** [comment]
![Snipaste_2023-12-05_18-43-13](https://github.com/MrXiaoM/Overflow/assets/35788433/233ab8e2-3922-4e97-b246-0a9871a0860f)

<details>
  <summary>文件结构</summary>

![Snipaste_2023-12-05_18-46-34](https://github.com/MrXiaoM/Overflow/assets/35788433/3cc7846b-6b7b-4313-8adf-bf7445203f29)

</details>

我手头没趁手的 Linux 环境，用 WSL 无法复现。

**Comment by Kesunorin** [comment]
重新下载尝试复现，奇迹地好了，可能是下载不完整（之前比较文件大小了），抱歉！
