### ISSUE TITLE
建议功能

### ISSUE THREAD

**Issue by 2055135** [MrXiaoM/Overflow#40]

**Comment by 2055135** [comment]
> 由于需要实现 mirai core api 以及登录接口本身的不可扩展性，无法实现，建议开两个

但如果是由插件来承担登录，overflow来负责转发，这种有可能实现吗？（其实是因为隔壁onebot-mirai没人修复bug）

**Comment by MrXiaoM** [comment]
> 但如果是由插件来承担登录，overflow来负责转发，这种有可能实现吗？（其实是因为隔壁onebot-mirai没人修复bug）

Overflow 是一个 mirai-core-api 实现，mirai 自带的协议实现已经删除了。

由于 Onebot 的资源管理与 mirai 十分不一样，协议跟 Overflow 是不能同时工作的，这样不仅很难实现，还会导致上传图片等等功能完全无法正常工作
