### ISSUE TITLE
关于`Image`类的一些讨论

### ISSUE THREAD

**Issue by EvolvedGhost** [MrXiaoM/Overflow#44]
### 问题描述

https://github.com/MrXiaoM/Overflow/blob/3bd5c2e2193ae3f20a4c46d113d38e21c55a72be/overflow-core/src/main/kotlin/top/mrxiaom/overflow/internal/Overflow.kt#L412-L416

正如代码注释所说`Onebot 没有 imageId 概念，Overflow 使用 imageId 字段来存储 Onebot 中的 file 链接`

但是在[df78661](https://github.com/MrXiaoM/Overflow/commit/df786619ac82b6f28a57bb633c1c3d70c775ae94)中仍然尝试进行了`imageId`的实现

这导致了一个问题，正如上文所言`Onebot 没有 imageId 概念`，也许在`Shamrock`中这类走手机协议的可以仍然保持`ImageId`的概念，但是在以`Lagrange`这类走PCNT协议的就会出现问题，因为PCNT的图片链接是这样的：
```
https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=Cgk3Mjc1MTEwNzASFDTLcVgFwCI96UKOYtmoY93wveXiGIY9IP8KKPXv0v-x_4UDUIC9owE&rkey=CAMSKLgthq-6lGU_NMvprHzoH2sjPb9AMHBJwViIt22qAznF1XoB9KY9IMk&spec=0
```

之前版本插件可以直接用`imageId`获取图片的方式来维持运行，或者直接从消息字符串中抽取链接，现在消息格式变了、`imageId`在`Lagrange`中获取变成了`!图片链接`而不是以前的`图片链接`，导致了部分混乱；

同时部分功能也是需要直接抽取图片外链，而以`Shamrock`中这类走手机协议的获取到的`imageId`也不能像以前一样简单的通过`https://gchat.qpic.cn/gchatpic_new/0/0-0-${imageId}/0`拼接获取外链。所以或许可以回滚这个commit，因为Onebot注定不能提供`imageId`的概念，强行解析`imageId`对于不同Onebot实现会产生不一致的效果导致更复杂的插件判断，或者额外提供一个接口直接获取图片链接保持其一致性

### 复现

用`Lagrange.Onebot`就会出现

### Overflow 版本

3bd5c2e

### 补充信息

对了，最新版本下我发送图片在Onebot传输中也变成了`{"type":"image","data":{"file":"!base64:///9j/4AAQXXXXXXXX"}}`，也是多了一个感叹号，我认为可能也是这个Commit导致的

**Comment by MrXiaoM** [comment]
通过 Image.queryUrl 依然是能正常取到图片链接的。
通过图片ID获取图片链接从来不是正确方式

**Comment by EvolvedGhost** [comment]
> 通过 Image.queryUrl 依然是能正常取到图片链接的。 通过图片ID获取图片链接从来不是正确方式

但是现在通过Lagrange的图片发送也会变成`!base64:///9j/4AAQXXXXXXXX`，很奇怪

**Comment by MrXiaoM** [comment]
我抽空排一下问题

**Comment by EvolvedGhost** [comment]
> > > 通过 Image.queryUrl 依然是能正常取到图片链接的。 通过图片ID获取图片链接从来不是正确方式
> > 
> > 
> > 但是现在通过Lagrange的图片发送也会变成`!base64:///9j/4AAQXXXXXXXX`，很奇怪
> 
> 我也遇到了这个问题

先回退到[49d2f29](https://github.com/MrXiaoM/Overflow/commit/49d2f29ec1de3946ffe6434c75000b431d75a5d1)吧，[maven](https://s01.oss.sonatype.org/content/repositories/snapshots/top/mrxiaom/overflow-core-all/2.16.0-49d2f29-SNAPSHOT/)，我这边试过这个版本没问题

**Comment by worksoup** [comment]
我在LLOneBot上使用，getMd5也受影响，因为md5似乎是通过imageId来计算的。

**Comment by MrXiaoM** [comment]
qqnt 的图片ID变化很大，不再考虑使用图片ID
