### ISSUE TITLE
临时会话消息接收不到

### ISSUE THREAD

**Issue by dysf888** [MrXiaoM/Overflow#48]
### 问题描述

![image](https://github.com/MrXiaoM/Overflow/assets/47450409/e7294743-5870-4a20-95c8-fa2361dc7665)
![image](https://github.com/MrXiaoM/Overflow/assets/47450409/12129bc5-af10-41b3-96f5-7f825f779e60)
![image](https://github.com/MrXiaoM/Overflow/assets/47450409/ab0f4ee5-3dee-4356-85d4-060aca25c436)

### 复现

不加好友，从群聊发起会话

### Overflow 版本

f454a28

**Comment by MrXiaoM** [comment]
把 issue 模板的信息补齐，截一个完整的图很难吗
