### ISSUE TITLE
无回复

### ISSUE THREAD

**Issue by DSLZL** [MrXiaoM/Overflow#58]
### 问题描述

在QQ群@机器人，带上/help或者help，以及私聊后，除了接收到qq发送过来的消息日志，无任何反应，例如发送help列表，ws接的是LLOneBot，以前用mirai是不会这样的，不知道什么原因，权限也给了

### 复现

如上

### Overflow 版本

6aaea6d-SNAPSHOT

### 其他组件版本

mirai-console：2.16.0
LLOneBot：v3.26.4

### 系统日志

```text
2024-05-31 09:53:10 V/Bot.: [Dragon Star] DSLZL -> [mirai:at:] /help
就这样，没有后续，使用其他插件的命令也一样
```

**Comment by MrXiaoM** [comment]
未安装 chat-command

**Comment by DSLZL** [comment]
都装了，http-api也有

**Comment by DSLZL** [comment]
是的，抱歉打扰了
