### ISSUE TITLE
PetPet插件兼容问题

### ISSUE THREAD

**Issue by Jieshsa** [MrXiaoM/Overflow#80]
### 问题描述

使用PetPet插件发送信息报错，插件作者觉得是Overflow兼容问题

### 复现

使用该插件https://github.com/Dituon/petpet

### Overflow 版本

b2f275f

### 其他组件版本

LLOnebot 3.26.5

### 补充信息

[2024-08-05.log](https://github.com/user-attachments/files/16490748/2024-08-05.log)

**Comment by MrXiaoM** [comment]
petpet 不好好上传流，而是用临时文件，上传完就删临时文件导致的问题
see https://mirai.mamoe.net/post/28247
