### ISSUE TITLE
自定义协议Event解析

### ISSUE THREAD

**Issue by KurenaiRyu** [MrXiaoM/Overflow#83]
我有看到 **Overflow 支持且仅支持连接到大多数标准的 Onebot 或 go-cqhttp 协议**，然后在对接LLOnebot当中遇到了自身发送消息是事件看起来是自己自定义了一个`post_type`，这里会引出一个问题：假如更多的协议做了一些自己的扩展，我就可能需要有一个地方能够对这些协议做补充，也就是希望能有一个入口添加一些自定义解析的事件。

**Comment by MrXiaoM** [comment]
[UnsolvedOnebotEvent.kt]https://github.com/MrXiaoM/Overflow/blob/main/overflow-core-api%2Fsrc%2Fmain%2Fkotlin%2Ftop%2Fmrxiaom%2Foverflow%2Fevent%2FUnsolvedOnebotEvent.kt

sdk 里面没有的事件都会广播到这里，但是 sdk 里面有的就不会。之后我会把 Overflow 已接收未处理的事件也加到这里
