### ISSUE TITLE
官网无法正常显示

### ISSUE THREAD

**Issue by HeJinDing-aipiao** [MrXiaoM/Overflow#89]
### 问题描述

![image](https://github.com/user-attachments/assets/e3a40f85-953b-48ed-968e-32ea0ffbed39)

### 复现

1.打开官网

### Overflow 版本

-

**Comment by MrXiaoM** [comment]
Github Pages 是这样的，刷新就完事

**Comment by HeJinDing-aipiao** [comment]
我刷新了也没用
![d2e0b25e342c008a97cb4f81eba9c323](https://github.com/user-attachments/assets/3bd54e85-2509-4930-b8ef-0b22162b0e57)

**Comment by MrXiaoM** [comment]
那只能说明你的网络或者浏览器有问题，我都能正常访问

**Comment by HeJinDing-aipiao** [comment]
应该是edge的问题,我手机开流量也无法访问

**Comment by HeJinDing-aipiao** [comment]
小米自带的浏览器成功访问了! 一定是EDGE干的!
