### ISSUE TITLE
对于gsk获取头像的支持

### ISSUE THREAD

**Issue by hlfzsi** [MrXiaoM/Overflow#93]
gsk的控制台输出中包含了若干信息，这些信息overflow并没有传递。
其中最重要的是头像地址，overflow仍采用QQ号拼接，这使得在使用gsk时插件无法获得用户头像。
请求：对gsk作为连接对象的情况进行特殊适配，默认使用gsk传递的头像地址，而不是mirai原生的QQ号拼接。
最近的构建中确实提供了获得原始json的方法，但mirai的外接SDK大都停止更新，无法进行调用。
如图为gsk接收消息时的控制台界面。nonebot是可以获得这些信息的，因此应当有方法获取。
![捕获](https://github.com/user-attachments/assets/127e9013-8e09-4b03-88df-515593a17c73)

**Comment by MrXiaoM** [comment]
636df16

**Comment by hlfzsi** [comment]
未能达到功能目的，目前返回的头像链接仍然是官方默认头像。

**Comment by hlfzsi** [comment]
刚刚我翻了下现在在用的SDK的代码，发现它头像获取是自己实现的QQ号拼接......看来是用不上了qwq

**Comment by hlfzsi** [comment]
想通过SDK拿openid也不现实，准备迁移到nonebot了

**Comment by MrXiaoM** [comment]
`get_avatar` 打错了 fc0a336

**Comment by MrXiaoM** [comment]
> 刚刚我翻了下现在在用的SDK的代码，发现它头像获取是自己实现的QQ号拼接......看来是用不上了qwq

你在哪看的，我看到的是，`get_avatar` 根据传入的 QQ 号参数获取 openid，然后跟 bot 的 QQ 号一起拼成头像链接，就跟你截图的那里一样

**Comment by hlfzsi** [comment]
如图
![捕获](https://github.com/user-attachments/assets/dbcf1cb3-facc-40a0-a71a-0cd47e8bc65a)

**Comment by hlfzsi** [comment]
我现在的SDK是没有办法拿到openid或者头像的

**Comment by MrXiaoM** [comment]
https://github.com/Hoshinonyaruko/Gensokyo/blob/main/handlers/get_avatar.go
